---
- name: Load core services list from role vars file
  ansible.builtin.include_vars: core_services.yml

- name: Combine core and optional services
  ansible.builtin.set_fact:
    all_services: "{{ core_services + optional_services }}"

- name: List all installed service and timer unit files
  ansible.builtin.command:
    cmd: systemctl list-unit-files --no-legend --type=service,timer
  register: all_unit_files
  changed_when: false
  check_mode: false

- name: Enable and start installed services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ all_services }}"
  when: item in all_unit_files.stdout
  loop_control:
    label: "{{ item }}"
