---
- name: Apply sysctl
  ansible.builtin.command:
    cmd: "sysctl --system"
  changed_when: false

- name: Load kernel modules
  ansible.builtin.command:
    cmd: "systemctl restart systemd-modules-load.service"
  changed_when: false
