---
- name: Deploy sysctl fragment
  ansible.builtin.template:
    src: sysctl.d.conf.j2
    dest: "{{ sysctl_path }}"
    owner: root
    group: root
    mode: "0644"
  notify: Apply sysctl

- name: Apply sysctl settings
  ansible.builtin.command:
    cmd: "sysctl -p {{ sysctl_path }}"
  register: sysctl_apply
  changed_when: "'Applying' in sysctl_apply.stdout or sysctl_apply.rc == 0"
