---
- name: Install AUR packages via paru
  become: true
  become_user: "{{ target_user }}"
  environment:
    PARU: "1"
  command:
    cmd: "paru -S --needed --noconfirm {{ aur_packages | join(' ') }}"
  when: aur_packages | length > 0
  changed_when: false
  check_mode: false
  register: aur_install
  failed_when: aur_install.rc != 0
