---
- name: Install official packages
  ansible.builtin.include_tasks: pacman.yml
  tags: [packages, pacman]

- name: Install AUR packages
  ansible.builtin.include_tasks: aur.yml
  tags: [packages, aur]

- name: Conditionally install bluetooth
  ansible.builtin.include_tasks: bluetooth.yml
  tags: [packages, bluetooth]

- name: Configure cloud-init and qemu-guest-agent when running in a VM
  ansible.builtin.include_tasks: cloud_init.yml
  when: vm_services | length > 0
  tags: [packages, cloud-init]

- name: Conditionally install i915-sriov driver
  ansible.builtin.include_tasks: i915-sriov.yml
  tags: [packages, i915-sriov]
