---
- name: Install Thunar file manager and extensions
  community.general.pacman:
    name: "{{ thunar_packages }}"
    state: present
    update_cache: true
  tags: [packages, thunar]

- name: Enable udisks2 service
  ansible.builtin.systemd:
    name: udisks2.service
    enabled: true
    state: started
  register: udisks2_service
  failed_when: udisks2_service is failed and not ansible_check_mode
  tags: [packages, thunar]
