---
- name: Configure user groups
  ansible.builtin.include_tasks: groups.yml
  tags: [user, groups]

- name: Configure login shell
  ansible.builtin.include_tasks: shell.yml
  tags: [user, shell]

- name: Configure sudoers
  ansible.builtin.include_tasks: sudoers.yml
  tags: [user, sudoers]

- name: Configure polkit
  ansible.builtin.include_tasks: polkit.yml
  tags: [user, polkit]
