---
- name: Regenerate initramfs
  become: true
  ansible.builtin.command:
    cmd: "mkinitcpio -P"
  changed_when: false

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart xrdp
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - xrdp.service
    - xrdp-sesman.service
