---
- name: Ensure /etc/NetworkManager/system-connections exists
  ansible.builtin.file:
    path: /etc/NetworkManager/system-connections
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Deploy NetworkManager connection profiles
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/NetworkManager/system-connections/{{ item | basename }}"
    owner: root
    group: root
    mode: "0600"
  with_fileglob:
    - "nmconnection/*.nmconnection"
  notify: Reload NetworkManager
  loop_control:
    label: "{{ item | basename }}"
