---
- name: Bootstrap EndeavourOS i3wm workstation
  hosts: localhost
  become: true
  gather_facts: true
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    all_proxy: "{{ lookup('env', 'all_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  roles:
    - role: packages
    - role: mise
    - role: services
    - role: network
    - role: kernel
    - role: user
    - role: display
